network/urls.py
from django.urls import include, path
from . import views, api, db_admin, sandbox

app_name = 'network'
urlpatterns = [
    # views paths
    path("", views.entry, name="entry"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("profile/<int:user_id>/<str:requested_newsfeed>", views.profile, name='profile'),
    # path("all_posts", views.all_posts, name="all_posts"),

    # Javascript API paths
    path('get_user_profile', api.get_user_profile, name='get_user_profile'),
    path('update_profile', api.update_profile, name='update_profile'),  
    path('follow/<int:user_id>', api.follow_user, name='follow_user'),
    path('unfollow/<int:user_id>', api.unfollow_user, name='unfollow_user'), 
    path('handle_post', api.handle_post, name='create_post'),  
    path('handle_post/<str:post_option>/<int:post_id>', api.handle_post, name='edit_post'),  
    path('remove_post/<int:post_id', api.remove_post, name='remove_post'),
    path('get_newsfeed_page/<int:user_id>/<str:postfeed>/<int:requested_page>', api.get_newsfeed_page, name = 'get_newsfeed_page'),
    path('upduke_post/<int:post_id>', api.upduke_post, name='upduke_post'),
    path('get_post_data/<int:post_id>', api.get_post_data, name = 'get_post_data'),
    
    # db_admin paths
    path('db_admin', db_admin.db_admin, name='db_admin'),
    path('insert_users', db_admin.insert_users, name='insert_users'),
    path('reset_su', db_admin.reset_su, name='reset_su'),
    path('inactive', db_admin.inactive, name='inactive'),
    path('delete_all', db_admin.delete_all, name='delete_all'),
    path('insert_text_posts', db_admin.insert_text_posts, name='insert_text_posts'),
    
    # sandbox
    path('many2many', sandbox.many2many, name='many2many'),
    path('gen_qs', sandbox.gen_qs, name='gen_qs'),
    
    #default
    path("index", views.entry, name='index'),
        
]

project4/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import include, path
from . import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("network.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


"""
if settings.DEBUG:
   import debug_toolbar
   urlpatterns = [
       path('__debug__/', include(debug_toolbar.urls)),
       # ...
   ] + urlpatterns
"""

network/views.py
# Standard
from django.conf import settings
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.shortcuts import redirect, get_object_or_404
import re

# Authentication
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

# Database
from django.db import IntegrityError
from django.core.paginator import Paginator
from .models import *

# File Handling
from django.core.files.storage import default_storage
from django.core.exceptions import SuspiciousFileOperation
import os

# Forms
from django.views.decorators.csrf import csrf_exempt
from .forms import *

# Image Handling
from PIL import Image
from django.core.files import File
from django.core.files.images import ImageFile


# There are a lot of Django Queries here
# https://docs.djangoproject.com/en/dev/topics/db/queries/





def entry(request):
    # If user is authenticated load profile
    if request.user.is_authenticated:
        current_user = User.objects.get(pk = request.user.id)
        print(f"############# current user => {current_user}")
        user_profile = User_Profile.objects.get(user_id_fk = current_user)
        profile_id = user_profile.user_profile_id
        user_name = current_user.username
        return HttpResponseRedirect(reverse("network:profile", kwargs={'user_id':current_user.pk, 'requested_newsfeed': 'homeposts'}))
    else:
        # load authentication options
        return render(request, "network/authenticate_options.html")



def index(request):
    return render(request, "network/index.html")


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            current_user = User.objects.get(pk = request.user.id)
            return HttpResponseRedirect(reverse("network:profile", kwargs={'user_id':current_user.pk, 'requested_newsfeed': 'allposts'}))
        else:
            return render(request, "network/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "network/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("network:entry"))



def sanitize_user_input(user_input):
    # Remove any characters that could be used for directory traversal or other malicious purposes
    # For example, you can remove '..' and '/' characters
    sanitized_input = re.sub(r'\.\.|/', '', user_input)
    
    # You can add additional validation or sanitization logic as needed

    return sanitized_input


def create_user_profile(request):
    print (f"#### create_user_profile ####")
    
    # Define filesystem directory tree for the users uploads
    # At this point The user has been entered in the User table and has been logged in
    current_user = User.objects.get(pk = request.user.id)
    username = current_user.username   
       
    # its also important to remember where you have defined MEDIA_ROOT and MEDIA_URL for user uploads
    # MEDIA_ROOT is where the app will upload files
    # MEDIA_URL is the root url realtive to the project root directory. This is where it will look for files when you give it a pathname such as a username
    media_root = settings.MEDIA_ROOT
    media_url  = settings.MEDIA_URL
    print(f"MEDIA_ROOT => {media_root}") # /home/artillery/webdev-apps/courses/CS50/Project-4/network/user_profiles
    print(f"MEDIA_URL => {media_url}")   # /user_profiles/     
       
    # Create an instance in the User_Profile table and assign defaults where necessary
    try:
        
        folder = os.path.join(media_url,username)
        web = 'http://www.'
        mon = username
        cap = 'Hello world, my name is '+ username + ' and I just arrived'
        
        # user1.pic.save('abc.png', File(open('/tmp/pic.png', 'r')))

        new_user_profile = User_Profile(user_id_fk = current_user,
                                        user_profile_folder = folder,
                                        website = web,
                                        moniker = mon, 
                                        caption = cap)
        new_user_profile.save()
        
        # Load the Default Avatar into the avatar ImageField
        image_path = os.path.join(media_root, 'default', 'av.jpg')
        if os.path.exists(image_path):
            with open(image_path, 'rb') as image_file:
                avatar_file = File(image_file)
                image_name = f"{current_user.pk}_{current_user.username}__av.jpg"
                new_user_profile.avatar.save(image_name, avatar_file) 
        else:
            print(f"Default Background Image Path Does Not Exist. Tried -> {image_path}")
            error = "Default Background Image Path Does Not Exist. Tried ->" + image_path
            
        # Load The Default Background Image into the background_img ImageField
        image_path = os.path.join(media_root, 'default', 'bg.jpg')
        if os.path.exists(image_path):
            print(f"Default bg_img Path exists")
            
            # Snatizing is not really necessary here, its just for information
            # Sanitize the input to remove potentially dangerous characters
            safe_input = sanitize_user_input('bg.jpg')  
            # Check if the sanitized input is still safe
            if not safe_input:
                error = "Detected path traversal attempt" + image_path
                raise SuspiciousFileOperation("Detected path traversal attempt")
                

            image_path = os.path.join(settings.MEDIA_ROOT, 'default', safe_input)
            with open(image_path, 'rb') as image_file:
                bg_image_file = File(image_file)
                image_name = f"{current_user.pk}_{current_user.username}__bg_img.jpg"
                new_user_profile.background_img.save(image_name, bg_image_file)
        else:
            print(f"Default bg_img path Does Not Exist. Tried => {image_path}")
            error = "Default Background Image Path Does Not Exist. Tried ->" + {image_path}
            
    except IntegrityError:
        # delete the user profile directory area
        # delete User
        return render(request, "network/register.html", {
            "message": "Error creating User Profile.",
            'error': error,
        })
        
    return
    

def register(request):
    print(f"#### register ####")      
        
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]
        
        #Django validation checks username is unique

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        
        if password != confirmation:    
            return render(request, "network/register.html", {
                "message": "Passwords must match."
            })
            
        # Check if email address is already in use
        email_address_is_taken = User.objects.filter(email = request.POST['email'])
        if email_address_is_taken:
                context_dictionary = {"message": "email already being used."}
                return render(request, "network/register.html", context_dictionary)
            
        # TODO Confirm and Validate Registration by email/phone

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()

        except IntegrityError:
            # remove the user profile directory area
            return render(request, "network/register.html", {
                "message": "Username already taken."
            })
            
        login(request, user)
        create_user_profile(request)
        return HttpResponseRedirect(reverse('network:profile', kwargs={'user_id': user.pk, 'requested_newsfeed':'allposts'}))
    else:
        return render(request, "network/register.html")
    
def page_404(request, message):
    pass
    
@login_required   
def profile(request, user_id, requested_newsfeed):
    print(f"##### profile #####")
    ## current_user - The currently logged in user
    ## requested_profile - The User that the profile belongs to

    # establish who active user is
    current_user_instance = User.objects.get(pk = request.user.id)

    # establish who the profile belongs to
    try:
        requested_profile_instance = User.objects.get(pk = user_id)
        print(f"profile_user {requested_profile_instance}")
    except:
        print(f"Cant fint Profile {user_id}")
        error_message = f"Can't find page for user {user_id}"
        return render(request, "network/page_404.html", {'error_message': error_message})
      
    # get User_Profile instance from User_Profile
    user_profile_instance = User_Profile.objects.get(user_id_fk = requested_profile_instance)
    
    # get cuurent_users User_Profile
    current_users_User_Profile = User_Profile.objects.get(user_id_fk = current_user_instance.pk)
    
    # Either the Profile is being viewed by the Owner or another User
    # Display appropriate available functionality depending on who is viewing the profile

    # establish If this is the Home Profile
    print(f"curent user => {current_user_instance.pk}")
    print(f"profile_user = {requested_profile_instance.pk}")
    
    if current_user_instance.pk == requested_profile_instance.pk:
        user_is_home = True
    else:
        user_is_home = False
        
    if user_is_home:
        # Active Logged in User is viewing their own profile
        # Initialise the Edit Profile Form

network/templates/network/authenticate_layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <link rel="shortcut icon" href="#">
        <title>{% block title %}Authentication{% endblock %}</title>
         <link href="{% static 'network/css/style.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class='main-window-wrapper'>

            <div class="showcase-grid-wrapper">
                {% include 'network/front-page/showcase.html' %}
            </div>


            <div class = "network-main-flexbox">

                <div class="authenticate-main-wrapper">

                    <div class = "authenticate-hero-wrapper">
                        <img src="{% static 'network/images/logos/network-grey.svg' %}">
                    </div>
            
                    <div class = "site-enerjon">
                        <div class="network-title">network</div>
                        <div class="tagline">Get Connected</div>
                    </div>

                    {% block authenticate_panel %}
                    {% endblock %}
                </div>
            </div>


        </div>
    </body>
</html>

network/templates/network/authenticate_options.html
{% extends "network/authenticate_layout.html" %}
{% load static %}

{% block title %}
    network Authentication
{% endblock %}

{% block authenticate_panel %}



        <div class = "authenticate-login-wrapper">
            <a href="{% url 'network:login' %}"> 
                <div class = "login-btn authenticate-btn" id = 'login-btn'>Login</div>
            </a>
        
            <a href="{% url 'network:register' %}">
                <div class = "login-btn authenticate-btn" id = 'register-btn'>Register</div>
            </a>
        </div>


{% endblock %}

network/templates/network/db_admin.html
{% extends "network/db_admin_layout.html" %}
{%load static%}
{% block center_panel %}

    <section class='db-admin-wrapper'>

        <h1> DB Admin </h1>

        <div class="main-center-stage">
            <div class = 'restart-wrapper'>
                <div class='db-button-row'>

                    <a href="{% url 'network:inactive' %}">
                        <div class="curtain-btn db-button">
                            <div class="curtain-btn-hover-state" ></div>
                            <span>Reset To Basline</span>
                        </div>
                    </a>
                </div>

                <div class='db-button-row'>  

                    <a href="{% url 'network:insert_users' %}">
                        <div class="curtain-btn db-button">
                            <div class="curtain-btn-hover-state" ></div>
                            <span>Insert Users</span>
                        </div>
                    </a>

                    <a href="{% url 'network:reset_su' %}">
                        <div class="curtain-btn db-button">
                            <div class="curtain-btn-hover-state" ></div>
                            <span>Reset SU</span>

                        </div>
                    </a>

                    <a href="{% url 'network:insert_text_posts' %}">
                        <div class="curtain-btn db-button">
                            <div class="curtain-btn-hover-state" ></div>
                            <span>Insert Text Posts</span>
                        </div>
                    </a>    

                    <a href="{% url 'network:inactive' %}">
                        <div class="curtain-btn db-button">
                            <div class="curtain-btn-hover-state" ></div>
                            <span>Inactive</span>
                        </div>
                    </a>

                    <a href="{% url 'network:inactive' %}">
                        <div class="curtain-btn db-button">
                            <div class="curtain-btn-hover-state" ></div>
                            <span>Inactive</span>
                        </div>
                    </a>
                </div>


                <div class='db-button-row'>
                    <a href="{% url 'network:delete_all' %}">
                        <div class="curtain-btn db-button db-delete">
                            <div class="curtain-btn-hover-state" ></div>
                        <span>Delete All</span>
                        </div>
                    </a>

                    <a href="{% url 'network:inactive' %}">
                        <div class="curtain-btn db-button db-delete">
                            <div class="curtain-btn-hover-state" ></div>
                        <span>Inactive</span>
                        </div>
                    </a>

                    <a href="{% url 'network:inactive' %}">
                        <div class="curtain-btn db-button db-delete">
                            <div class="curtain-btn-hover-state" ></div>
                        <span>Inactive</span>
                        </div>
                    </a>
                </div>
                <div class='db-button-row'>
                    <div class='footer'>{{message}}</div>
                </div>
            </div>

        </div>
    
    </section>
    
 
    


{% endblock %}

network/templates/network/db_admin_layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}network Database Admin{% endblock %}</title>
         <link href="{% static 'network/css/style.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class='main-window-wrapper'>
            {% block center_panel %}

            {% endblock %}
        </div>
    </body>
</html>

network/templates/network/index.html
{% extends "network/layout.html" %}

{% block center_panel %}
    <span>TODO</span>
 
<!--
    <div class='debug-window'>
        <p id="viewsize"></p>
    
        <script>
        var w = window.innerWidth;
        var h = window.innerHeight;
        
        var x = document.getElementById("viewsize");
        x.innerHTML = "Browser width: " + w + ", height: " + h + ".";
        </script>
    
        <div class='debug-msg'>
            {{error_message|safe}}
        </div>
    </div>
-->

<!-- Buttons at top One for ALl Posts and One for Following Posts-->


{% endblock %}

{% block additional %}
    <span>TODO</span>
{% endblock %}

network/templates/network/login.html
{% extends "network/authenticate_layout.html" %}

{% block authenticate_panel %}

    <div class="login-page-wrapper">
        <div class="login-title">
            Login
        </div>

        <div class="login-form-wrapper">
            <form class ="login-form" action="{% url 'network:login' %}" method="post">
                {% csrf_token %}
                <input autofocus class="authentication-form-input" type="text" name="username" placeholder="Username">
                <input class="authentication-form-input" type="password" name="password" placeholder="Password">
                <input class = "login-btn" type="submit" value="Login">
            </form>
            {% if message %}
            <div class="login-message">{{ message }}</div>
        {% endif %}
        </div>

        <div class="authenticate-redirect">
            <div>Don't have an account?</div>
            <div> <a href="{% url 'network:register' %}">Register here.</a></div>
        </div>

    </div>

{% endblock %}

network/templates/network/main_layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <link rel="shortcut icon" href="#">
        <title>{% block title %}network Social Network{% endblock %}</title>
         <link href="{% static 'network/css/style.css' %}" rel="stylesheet">

    </head>
    <body>
        <div class='main-window-wrapper'>

            {%if user.is_authenticated == False %}
                <div class="showcase-grid-wrapper">
                    {% include 'network/front-page/showcase.html' %}
                </div>
            {% endif %}

            <div class = "network-main-flexbox">

                <div class="left-nav-panel">
                    {%block left_panel%}

                    {%endblock%}
                </div>
                
                <div class="center-main-panel">
                    
                    {% block center_panel %}
                    {% endblock %}
                </div>
<!--
                <div class="right-additional-panel">

                    {% block additional %}
                    {% endblock %}
                </div>
-->
            </div>
        </div>
    </body>
</html>

{% block script %} {% endblock %}

network/templates/network/nav_panel.html
{% load static %}

<div class = 'nav-top-section'>
    <div class = "profile-enerjon">
        <div class = "nav-logo-wrapper">
            <img src="{% static 'network/images/logos/network-orange.svg' %}">
        </div>

         <div class="network-title">Network</div>
         
    </div>
</div>


<div class = 'nav-middle-section'>

    <div class = "nav-link" id = "post-btn">
        <div class = 'nav-item-icon'>
            <img src="{% static 'network/images/nav_icons/pencil.png' %}">
        </div>
        <div class = "nav-label desktop-only">
            Post
        </div>
    </div>


    <a href = "{% url 'network:profile' current_user_id 'allposts' %}">
        <div class = "nav-link" id = 'all-posts-btn'>
            <div class = 'nav-item-icon'>
                <img src="{% static 'network/images/nav_icons/globe_black.svg' %}">
            </div>
            <div class = "nav-label desktop-only">
                All Posts
            </div>
        </div>
    </a>

    <a href = "{% url 'network:profile' current_user_id 'frensposts' %}">
        <div class = "nav-link" id = 'follower-posts-btn'>
            <div class = 'nav-item-icon'>
                <img src="{% static 'network/images/nav_icons/friends.png' %}">
            </div>
            <div class = "nav-label desktop-only">
                Muse Feed
            </div>
        </div>
    </a>

    <div class = "nav-link" id = "notifications-btn">
        <div class = 'nav-item-icon'>
            <img src="{% static 'network/images/nav_icons/notification.png' %}">
        </div>
        <div class = "nav-label desktop-only">
            Notifications
        </div>
    </div>

    <div class = "nav-link" id = "messages-btn">
        <div class = 'nav-item-icon'>
            <img src="{% static 'network/images/nav_icons/mail.png' %}">
        </div>
        <div class = "nav-label desktop-only">
            Messages
        </div>
    </div>

    <div class = "nav-link" id = "noticeboard-btn">
        <div class = 'nav-item-icon'>
            <img src="{% static 'network/images/nav_icons/noticeboard.png' %}">
        </div>
        <div class = "nav-label desktop-only">
            Noticeboard
        </div>
    </div>

    <div class = "nav-link" id = "search-btn">
        <div class = 'nav-item-icon'>
            <img src="{% static 'network/images/nav_icons/search.png' %}">
        </div>
        <div class = "nav-label desktop-only">
            Search
        </div>
    </div>
</div>


<div class = 'nav-bottom-section'>

        <a href="{% url 'network:profile'  user.pk 'homeposts' %}">
            <div class = 'small-avatar-wrapper'>
                <div class = 'small-avatar'>
                    <img src = "{{current_user.avatar.url}}">
                </div>
            </div>
        </a>

        <div class = "link-wrapper">

            <a class = "nav-link" id = 'user-profile-btn' href="{% url 'network:profile'  user.pk 'homeposts' %}">


                <div class = 'nav-item-icon'>
                    <img src="{% static 'network/images/nav_icons/profile-user.png' %}">
                </div>


                <div class = "nav-label desktop-only">
                    {{ user.username }}
                </div>
            </a>
        </div>

        <div class = "link-wrapper">
            <a class = "nav-link" id = "logout-btn" href="{% url 'network:logout' %}">
                <div class = 'nav-item-icon'>
                    <img src="{% static 'network/images/nav_icons/logout-red.svg' %}">
                </div>
                <div class = "nav-label desktop-only">
                    Logout
                </div>
            </a>
        </div>

</div>

network/templates/network/post_ob.backup.html
{% load static%}

{% for post in page_obj%}

<div class = 'feedpost-wrapper newsfeed-pg{{page_num}}' data-post_id = {{post.user_post_id}}>
    <a href="{% url 'network:profile' post.user_id_fk.pk 'homeposts' %}">
        <div class = 'feedpost-header'>
            <div class = 'feedpost-avatar-wrapper'>
                <img class = 'feedpost-avatar' src = "{{ post.user_id_fk.user_profile.first.avatar.url  }}">
            </div>
            <div class = 'feedpost-username'>{{post.user_id_fk.username}}</div>
        </div>
    </a>

    <div class = 'feedpost-body'>
        <div class = 'feedpost-title'>{{post.title}}</div>
        <div class = 'feedpost-message'>{{post.message}}</div>
        {% if post.image_file %}
            <div class = 'feedpost-image_wrapper'>
                <img class = 'feedpost-image' src ="{{post.image_file.url}}">
            </div>
        {% endif %}

    </div>
    <div class = 'feedpost-footer'>
        <div class = "star-icon-wrapper">
            <img class='star-icon' src = "{% static 'network/images/post_icons/star_grey.svg' %}">
        </div>
        <div class = 'upduke-count'>
            {{post.engagement.upduke}}
        </div>
        <div class = 'feedpost-date-wrapper'>
            <div class = 'feedpost-date'>{{post.date}}</div>
        </div>
    </div>


</div>
{%endfor%}

network/templates/network/post_obj.html
{% load static%}



<div class = 'feedpost-wrapper newsfeed-pg{{page_num}}' data-post_id = {{post.user_post_id}}>
    
    <a href="{% url 'network:profile' post.user_id_fk.pk 'homeposts' %}">
        <div class = 'feedpost-header'>
            <div class = 'feedpost-avatar-wrapper'>
                <img class = 'feedpost-avatar' src = "{{ post.user_id_fk.user_profile.first.avatar.url  }}">
            </div>
            <div class = 'feedpost-username'>{{post.user_id_fk.username}}</div>
        </div>
    </a>

    <div class = 'feedpost-body'>
        <div class = 'feedpost-title'>{{post.title}}</div>
        <div class = 'feedpost-message'>{{post.message}}</div>
        {% if post.image_file %}
            <div class = 'feedpost-image-wrapper'>
                <img class = 'feedpost-image' src ="{{post.image_file.url}}">
            </div>
        {% endif %}
    </div>


    <div class = 'feedpost-footer'>


        {% if upduke_star_status == 'on' %}
            <div class = "star-icon-wrapper">
                <img class='star-icon  star-icon-active' src = "{% static 'network/images/post_icons/star_grey.svg' %}">
            </div>
        {% else %}
            <div class = "star-icon-wrapper">
                <img class='star-icon' src = "{% static 'network/images/post_icons/star_grey.svg' %}">
            </div>
        {% endif %}

        <div class = 'upduke-count'>
            {% if post.engagement_m2m_post_set.exists   %}
                {{total_updukes}}
            {% else %}
                0
            {% endif %}
        </div>

        {% if post_is_by_current_user %}
            <div class = 'edit-post-wrapper'>
                    <img class ="edit-post-icon" src = "{% static 'network/images/post_icons/edit-grey.svg'%}">
            </div>

            <div class = 'delete-post-wrapper'>
                <img class ="delete-post-icon" src = "{% static 'network/images/post_icons/delete-grey.svg'%}">
            </div>
        {% endif %}




        <div class = 'feedpost-date-wrapper'>
            <div class = 'feedpost-date'>{{post.date}}</div>
        </div>
    </div>


</div>

network/templates/network/register.html
{% extends "network/authenticate_layout.html" %}

{% block authenticate_panel %}

    <div class="login-page-wrapper">
        <div class="login-title">
            Register
        </div>



        <div class="register-form-wrapper">
            <form class='regsier-form' action="{% url 'network:register' %}" method="post">
                {% csrf_token %}
                <input class="authentication-form-input" autofocus type="text" name="username" placeholder="Username">
                <input class="authentication-form-input" type="email" name="email" placeholder="Email Address">
                <input class="authentication-form-input" type="password" name="password" placeholder="Password">
                <input class="authentication-form-input" type="password" name="confirmation" placeholder="Confirm Password">
                <input class = "login-btn" type="submit" value="Register">
            </form>

            {% if message %}
                <div class="login-message">{{ message }}</div>
            {% endif %}
        </div>

        <div class="authenticate-redirect">
            <div>Already have an account?</div>
            <div> <a href="{% url 'network:login' %}">Log In here.</a></div>
        </div>
    </div>

{% endblock %}

network/templates/network/sandbox_layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <link rel="shortcut icon" href="#">
        <title>{% block title %}Sandbox{% endblock %}</title>
         <link href="{% static 'network/css/style.css' %}" rel="stylesheet">
    </head>
    <body>

        {% block sandbox%}
        {%endblock%}

    </body>
</html>